### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [ayakuma309/BookBuzz#63]
@ayakuma309 
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
ジャンル一覧から探す際に500エラーになるのでご確認ください。
いい感じに世界観が出ているアプリになっていますね。ランダムで紹介もされるし、UIもとてもいいです！

## 静的コードチェックが入っている
rubocop導入していますね、まだコードチェックが通されてない箇所があるのでコードチェックしておきましょう。

## 就活において十分な技術力を示せる機能を実装しているか
レコメンドのロジックはしっかり考えて組めていますね！
もう一つ強めの機能があると安心かなといったところです。

下記に気になる点を挙げたのでご確認ください。

- tagsテーブルのnameカラムはnull制約つけておきましょう。
- bookモデルのfind_similar_booksメソッドでeachで回している部分はmapやrejectなどのメソッドで代わりになるかなと思うのでリファクタしておきましょう。
- インデントがずれている箇所があるので修正しておきましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
世界観が出て本の見た目もおしゃれです！
ちょっと気になる点だけ挙げておきますね！

 - TOPページのメニューが左側によっているのは、何か右側にあるのかなといった印象なのですが、何もないのでちょっと違和感あるかもくらいです（そこまで気にしなくてOKです）

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by ayakuma309** [comment]
レビューしてくださりありがとうございます！
とてもとても嬉しいです☺️
色々と不備があり申し訳ございません😭
ジャンル一覧から探す際に500エラーは原因が分かったので変更して反映させました🙇‍♀️
ありがとうございます🙇‍♀️
issue追加しました。
よろしくお願いします。
もう一つ強めの機能つけて本リリースは1週間〜10日後に頑張ります。
よろしくお願いします🙇‍♀️

**Comment by kerochelo** [comment]
@ayakuma309 
承知しました、この調子で頑張って進めていきましょう:+1:
